### ISSUE TITLE
Local Aggregator

### ISSUE THREAD

**Issue by RichShumaker** [erwanm/tw-aggregator#25]
I am on a Windows 8 PC.
Is there a way to create a local aggregator?
I am working on putting things onto a Raspberry Pi Server, I see it being helpful to put locally as well.

Thanks.
Rich Shumaker

**Comment by erwanm** [comment]
For Windows I'm really not sure that my script would be the best solution: first you would have to make Bash work somehow, see e.g. http://superuser.com/questions/608106/how-can-i-use-a-bash-like-shell-on-windows. and then probably there would be other issues to make everything work... I'm really not familiar with developing in Windows, but it might be easier to rewrite a windows-specific version of my scripts rather than going through all the adaptation.

On a Raspberry Pi I would definitely suggest installing a Linux, the script should work easily.

**Comment by RichShumaker** [comment]
Makes perfect sense and I will work on implementing this on my RasPi.  Would be a great feature to have a teach be able to watch over students or a group to work individually but see what they are doing together.

This issue or upgrade closed as it is beyond the scope of this software.
If anyone wants to do this for Windows I recommend forking this and starting an aggregator for Windows.
