### ISSUE TITLE
Server Scrape for the Bash List

### ISSUE THREAD

**Issue by RichShumaker** [erwanm/tw-aggregator#35]
If I understand how this works you have a list of all the TW5 that you grab at a set time.
I wonder if you could automate the list by grabbing all the TW5 off the server in a specific folder?

I am trying to create an aggregator for the Raspberry Pi that would have all the TW5 on the server.
Instead of manually saying here is the TW5 the system could see all of them in specific folders and grab them.

I know that this would not work for yours as you are grabbing from around the web on many different servers.

Usage case for this is a small group all using TiddlyWiki to allow them to search each others work to see if anyone has done what you want to do.  Also for a teacher so they could assign something and everyone would TAG it or Name it the same and then the teacher could search and grab them all quickly and easily.

It would be cool to be able to dump all the Tiddlers to another spot as well, JSON the data to another location.
Dag nab it that is another thing.  I will let this hang in the air for a bit as it is something different than I am asking here.

Rich Shumaker

**Comment by erwanm** [comment]
I could easily add the possibility to grab a local wiki specified with a path instead of an url. 

However, if I understand you correctly, it seems to me that you don't need the aggregator to do that: with the node.js edition of TW you can already specify several paths where tiddlers are stored, and this way you can have many individual wikis seen as one big wiki with all the tiddlers (you can't write to these individual wikis, but anynway it's not something you want to do). See http://tiddlywiki.com/#TiddlyWikiFolders, and the includeWikis option in particular. 

As far as I can tell, the only disadvantages compared to using the aggregator for this task are:
* it is not possible to have two tiddlers from two different wikis with the same title: I had tested this case and what happens is that only the first one is visible from the "big wiki". In the aggregator this problem is solved by adding a prefix (the wiki id) to the tiddlers.
* I'm not totally sure, but I think that all your individual wikis must be node.js edition as well (whereas the aggregator does the conversion itself).

the advantage of the simple node.js TW version is that it's much simpler, of course: you wouldn't depend on changes in the aggregator code, and probably avoid a few bugs ;)

**Comment by erwanm** [comment]
I implemented the feature (ability to scrap a local wiki) in the aggregator. you just specify the path instead of the url, but be careful you need to use an absolute path (relative path would be quite more work because of how it's done currently)

**Comment by RichShumaker** [comment]
Thank you and I will work on testing this out as you can tell I am behind, #heheh
