### ISSUE TITLE
Tags with special meaning

### ISSUE THREAD

**Issue by felixhayashi** [erwanm/tw-aggregator#36]
Hi @erwanm,

would it be possible to introduce a tag like e.g. "#news" or "#release notes" that can be used by wiki-owners to force some tiddlers to be listed chronologically as a separate category in your search wiki? Mat already suggested a similar thing but then it would be possible for plugin developers to tag release note tiddlers with #news and people can see what is happening - this is actually pretty close to a RSS-feed.

-Felix

Probably related to #34

**Comment by erwanm** [comment]
Yes, I'm thinking about something like that as well. Originally I was going to simply use the data of the tiddler to automatically generate a "news event".

I think the difficulty lies mostly in how this features fits with different cases:

* automatic "news" when a plugin is updated based on the date
* some authors might not want to use it although their plugins are useful, so it's important that users don't assume that this kind of news will show up for all plugins
* people could forget to remove their "news" tag when it's not news anymore, so the system problably has to do some cleanup based on the date
* possibly storing the news to keep track of the history?

Also it's probably better to propose a special tiddler where the author can write their own filter instead of a predefined tag, since it's more generic and gives more freedom to the author.

I'm trying to clarify for myself how to make all this work nicely together, anybody is welcome to give their suggestions!

**Comment by felixhayashi** [comment]
Hi @erwanm,

thanks for sharing some thoughts on this

> Originally I was going to simply use the date of the tiddler to automatically generate a "news event".

I think this would spam the results

> automatic "news" when a plugin is updated based on the date

Well, how do you know which plugin and which wiki to trace?

> some authors might not want to use it although their plugins are useful, so it's important that users don't assume that this kind of news will show up for all plugins

Don't worry, if plugin developers don't use the tag for some reason, other people can simply jump in and create a news tiddler - even though they don't develop the plugin.

> people could forget to remove their "news" tag when it's not news anymore, so the system problably has to do some cleanup based on the date

I suggest the following: Use an each filter on the created day and sort by creation date (just like the recent tab in tiddlywiki does it). If information is too old, say one month, you simply don't display it anymore. Who cares if people forget to remove the news tag? Actually, when working with CMS like Joomla etc. you do not remove the tag but the news simply get pushed down.

> possibly storing the news to keep track of the history?

Yes, an archive would be great, like Thunderbird does it: All emails (in our case news) of a year are put into a separate file bundled by year (in our case tiddler). But this would be community search 2.0 I guess.

> Also it's probably better to propose a special tiddler where the author can write their own filter instead of a predefined tag, since it's more generic and gives more freedom to the author.

This would be great of course, similar to your whitelist mechanism. But I would say if you cannot find a filter in the owner's wiki, you scan for something like "#news" or "news" as fallback and just tell everybody that this is the default tag to make it into your news category.

> I'm trying to clarify for myself how to make all this work nicely together, anybody is welcome to give their suggestions!

Of course, try to make good design choices now. :)

-Felix

**Comment by erwanm** [comment]
done.
implemented in a simple way which corresponds to the original idea, I think.
