### ISSUE TITLE
add short plugin info to authors and/or wikis lists

### ISSUE THREAD

**Issue by erwanm** [erwanm/tw-aggregator#63]
possibly only number of plugins, or simple list with links (with text = plugin title).

**Comment by twMat** [comment]
Not only that;

just like you have the [follow url fature](http://erwanm.github.io/tw-community-search/#FollowUrlFeature), the author could include a special "About" tiddler. This tiddler is *actually* included on the tw-aggreagator site! and gives the author an opportunity to present the creation in a desirable way. 

I guess the About shoudl include a local stylesheet (simple; just put it `<style>` here `</style>` in the very tiddler).

This would add a lot more "flavor" to the TW Community Aggreagator site. BTW, this could be an appropriate location for the TW Community Aggregator site to append a "Community Comments" #69  And it woudl make it appear closer to traditional plugin repositories.

**Comment by twMat** [comment]
...*and* for Authors themselves, I believe this is the *perfect* opportunity to start to use RichShumakers / JedCartys twCard ideas. I.e the tiddler [JedCarty](http://erwanm.github.io/tw-community-search/#JedCarty) could instead display his [twCard](http://ooktech.com/jed/externalbrain/#Jed%20Carty%20(inmysocks)) so that Jed has a chance to make people think he is a nice guy (hehe, good luck! ;-)

**Comment by twMat** [comment]
See #41 for my thoughts. (Did I post it to wrong issue?)

**Comment by erwanm** [comment]
sorry for my very vague description of issues, I get confused myself ;)

this one is only about linking wikis and/or authors to their list of plugins in the corresponding tiddlers

**Comment by erwanm** [comment]
This issue was moved to erwanm/tw-community-search#4
