### ISSUE TITLE
Permalink don't work for version < TW 5.0.11

### ISSUE THREAD

**Issue by erwanm** [erwanm/tw-aggregator#7]
*Felix noticed the problem with Stephan's wiki:*

Maybe a suggestion. When crawling the wikis, check for the version number as permalinks where introduced with the release of 5.0.11. So unfortunately stephan's http://tw5magick.tiddlyspot.com/#Geography%2006 doesn't navigate to the tiddler.

(from https://groups.google.com/d/msg/Tiddlywiki/tJjhzDDvk4k/8aW3rUMa8bUJ)

*I'm not sure what can be done about that though, except waiting for such wikis to be upgraded ;)*

**Comment by RichShumaker** [comment]
First thanks for adding my TW, it is on version 5.1.7.
Second I noticed that my permalinks are not working correct, 
I searched json and 'TiddlyWiki Hangout #012 @TWHangouts' came up when you click it the Spaces and # are not converted to permalink values so instead of being 
http://www.richshumaker.com/tw5/TiddlyWiki-Hangouts.html#TiddlyWiki%20Hangout%20%23012
it is
http://www.richshumaker.com/tw5/TiddlyWiki-Hangouts.html#TiddlyWiki Hangout #012
and therefore ends up at a page that doesn't exist.

Thank you.
Rich Shumaker

**Comment by erwanm** [comment]
Hi Rich,

thank you for catching that. I think it is only the "#" sign which makes the link fail, because there are many other titles withs spaces which work well (as far as I can see with firefox, at least)
I created a new issue #24 since it is a different problem.
I'll try to work on that soon since it's quite serious, but probably not before the week end.

**Comment by RichShumaker** [comment]
This seems to be working now.  I read that you had updated it so I wanted to post here that I tested it and it seems to work for my links.  Makes perfect sense about the # as I use them everywhere and if that character is an issue then the whole TW would be an issue.

**Comment by erwanm** [comment]
this issue died of old age: I don't have any wiki this old left in my list.
