### ISSUE TITLE
SERIOUS BUG: some tiddlers disappear in the conversion (?)

### ISSUE THREAD

**Issue by erwanm** [erwanm/tw-aggregator#71]
found that some tiddlers which exist in the node.js wiki seem to have disappeared in the standalone version. maybe something wrong with the format?

* tags exist and the count indicates N>0 tiddlers tagged with this tag, but the list (from the tag pill) is empty
* Example: "Tab index attribute" in TWaddle, tagged @TWaddle
** A TWCS search as well as an advanced search did not find anything
* in test mode, 1953 *.tid files in the node.js wiki, but only 1364 "indexed tiddlers"

**Comment by erwanm** [comment]
observations: 

* no error message during the conversion
* when converting back to node.js all the tiddlers appear
** btw an extra field 'revision' is added

**Comment by erwanm** [comment]
Zeroing on the cause: 

* apparently Mat's whole wiki disappeared
* seems to be the only one affected
* bug appeared very recently with system tags (good thing!)

**Comment by twMat** [comment]
Possibly relevant;

I use a **modified upload saver** because TWaddle is a public version of my admin version (to avoid public unfinished articles etc). This solution was suggested/provided by @jermolene [here](https://groups.google.com/d/msg/tiddlywiki/1S348N3rsAc/rbXjCZRB9HYJ). If this is relevant for the issue here then you might also want to have seen my [general proposal](https://github.com/Jermolene/TiddlyWiki5/issues/1755) for this, in case it is ever implemented.

I suspect I'm the only one who uses this so far which is why I suspect it might be relevant to this aggregator issue.

**Comment by erwanm** [comment]
Thank you Mat, it was actually yet another stupid mistake on my side: when creating tiddlers for any existing tags, the script was overwriting previously existing tiddlers with the same name. In the case of the special tiddlers named with the wiki ids, like "TWaddle", it was messing up everything.
